FROM nvcr.io/nvidia/tensorrt:23.01-py3

WORKDIR /app
COPY . /app
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

ADD https://web.lcrc.anl.gov/public/waggle/models/ptychonn/ptychoNN_8_128_fp16.trt /app/model_128.trt
ADD https://web.lcrc.anl.gov/public/waggle/models/ptychonn/ptychoNN_8_512_fp16.trt /app/model_512.trt
ADD https://web.lcrc.anl.gov/public/waggle/models/ptychonn/diff_scan_810.npy /app/scan.npy
ENV PYTHONPATH "${PYTHONPATH}:/app"
